manifest: manifests/freuid.parquet
backbone: convnextv2_tiny.fcmae_ft_in22k_in1k
model_type: rgb
train_aug: train
img_size: 384
batch_size: 24
epochs: 10
lr: 0.0003
weight_decay: 0.05
num_workers: 8
holdout_by: doc_type
holdout_values: "MOZAMBIQUE/DL"
val_sources: "freuid"
seed: 42
out_dir: checkpoints/exp_ema
amp: true
pretrained: true
ema: true
