amp: true
backbone: regnety_160.tv2_in1k
batch_size: 8
dtc_lambda: 0.5
epochs: 3
fda_p: 0.4
freeze_backbone: false
heavy_recapture: true
holdout_by: ''
img_size: 1120
lr: 5.0e-05
manifest: manifests/freuid_fid_capgen_e6.parquet
model_type: dtc
num_workers: 12
out_dir: checkpoints/exp_e6reg_fda1120_s44
pretrained: true
save_every_epoch: true
seed: 44
tracemix_p: 0.5
val_fraction: 0.1
weight_decay: 0.05
